version: '3.8'

services:
    tex:
        image: ghcr.io/xu-cheng/texlive-full
        working_dir: /source_files
        command: latexmk -pdf -c -shell-escape -output-directory=/output main.tex;
        volumes:
            - ./src:/source_files
            - ./output:/output
        network_mode: none
